import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {getServerSession} from "next-auth";
import {authOptions} from "@/src/app/api/auth/[...nextauth]/route";
import SessionProvider from "@/src/app/providers/SessionProvider";
import HeaderAuth from "@/src/app/components/HeaderAuth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Server Component
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Preload session on the server to avoid flicker
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <header>
            <h1 className="font-bold">Expense Tracker</h1>
            <HeaderAuth />
          </header>
          <main>{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
